### ISSUE TITLE
Issue setting initial DB

### ISSUE THREAD

**Issue by prendersnacks** [MadeInDreams-Team/rent-a-bot#1]
hey having fun with this code, looking to adapt some parts to another chain. However I am having issues right off the bat with mysql db. it seems unable to even do the initial check, as I get a "Cannot read property 'length' of undefined" at "if(res.length > 0)" in db-con.js . Even removing that and hard forcing the table creation didnt seem to work. any ideas?

**Comment by Madeindreams** [comment]
Hello!

Did you create a Database and connect to it? The connection credentials should be in the env.

res will contain the ERC assets. Once your connected to the DB. You should run a scan, it will fill the database with 0x Order Book

**Comment by prendersnacks** [comment]
I did yeah, I even tried to delete the intial check to have it just make the table, and it seems to connect but then says "could not create db" and errors out.

**Comment by Madeindreams** [comment]
did you set some right for your user account that you use in MYSQL?

**Comment by prendersnacks** [comment]
Yeah I even created the table and tried deleting the check and it still seems not to work.

**Comment by Madeindreams** [comment]
So it`s obvious your not connecting to it. Maybe your should turn it into a json file.  I suggest maybe change to MySQL pool to a regular single connection query. Or look into why your not able to resolve any of the query. Probably cause your not connected.
This issue is more a MySQL setup or connectivity issue than an issue from this code.
